#!/usr/bin/env bash
set -euo pipefail

# post-lint-comment.sh
# Posts lintro results as a PR comment.
#
# Usage:
#   PR_NUMBER=123 scripts/ci/post-lint-comment.sh
#
# Environment:
#   PR_NUMBER - The pull request number (required)
#   GH_TOKEN  - GitHub token with pull-requests:write (required)

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
	cat <<'EOF'
Posts lintro results as a PR comment.

Usage:
  PR_NUMBER=123 scripts/ci/post-lint-comment.sh

Environment:
  PR_NUMBER - The pull request number (required)
  GH_TOKEN  - GitHub token with pull-requests:write (required)

This script:
  1. Reads lintro-output.txt
  2. Formats it as a PR comment
  3. Posts or updates the comment on the PR

Exit codes:
  0 - Comment posted successfully
  1 - Error occurred
EOF
	exit 0
fi

if [[ -z "${PR_NUMBER:-}" ]]; then
	echo "Error: PR_NUMBER environment variable is required" >&2
	exit 1
fi

OUTPUT_FILE="lintro-output.txt"
COMMENT_MARKER="<!-- lintro-report -->"

if [[ ! -f "$OUTPUT_FILE" ]]; then
	echo "No lintro output file found, skipping comment"
	exit 0
fi

# Determine status
LINTRO_EXIT_CODE="${LINTRO_EXIT_CODE:-0}"
if [[ "$LINTRO_EXIT_CODE" -eq 0 ]]; then
	STATUS_EMOJI="✅"
	STATUS_TEXT="All checks passed"
else
	STATUS_EMOJI="❌"
	STATUS_TEXT="Issues found"
fi

# Build comment body
COMMENT_BODY="$COMMENT_MARKER
## $STATUS_EMOJI Lintro Report

$STATUS_TEXT

<details>
<summary>View full output</summary>

\`\`\`
$(cat "$OUTPUT_FILE")
\`\`\`

</details>

---
*Generated by [lintro](https://github.com/TurboCoder13/py-lintro)*"

# Find existing comment with marker
EXISTING_COMMENT_ID=$(gh api "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
	--jq ".[] | select(.body | contains(\"$COMMENT_MARKER\")) | .id" | head -1 || true)

if [[ -n "$EXISTING_COMMENT_ID" ]]; then
	echo "Updating existing comment (ID: $EXISTING_COMMENT_ID)"
	gh api "repos/${GITHUB_REPOSITORY}/issues/comments/${EXISTING_COMMENT_ID}" \
		-X PATCH \
		-f body="$COMMENT_BODY" >/dev/null
else
	echo "Creating new comment"
	gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY"
fi

echo "PR comment posted successfully"
